<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Linear Models (LM) | Introduction to statistical data analysis in R</title>
  <meta name="description" content="Intro to Stats with R" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Linear Models (LM) | Introduction to statistical data analysis in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Intro to Stats with R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Linear Models (LM) | Introduction to statistical data analysis in R" />
  
  <meta name="twitter:description" content="Intro to Stats with R" />
  

<meta name="author" content="Mario Recker" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-statistical-modelling-in-r.html"/>
<link rel="next" href="mixed-effect-models-mem.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<script language="javascript"> 
    function toggle(id) {
        var ele = document.getElementById("toggleText" + id);
        var text = document.getElementById("displayText" + id);
        var buttonText = text.innerHTML.replace("Show: ", "");
        buttonText = buttonText.replace("Hide: ", "");
        if(ele.style.display == "block") {
            ele.style.display = "none";
            text.innerHTML = "Show: " + buttonText;
        } else {
            ele.style.display = "block";
            text.innerHTML = "Hide: " + buttonText;
        }
    } 
</script>

<script language="javascript">
    function openCode(evt, codeName, id) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent" + id);
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks" + id);
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(codeName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

<script language="javascript">
    function hide(id){
        document.getElementById(id).style.display = "none";
    }
</script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">



<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#workshop-structure"><i class="fa fa-check"></i>Workshop structure</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html"><i class="fa fa-check"></i><b>1</b> General introduction to R/RStudio</a>
<ul>
<li class="chapter" data-level="1.1" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#setting-up-an-r-session"><i class="fa fa-check"></i><b>1.1</b> Setting up an R session</a></li>
<li class="chapter" data-level="1.2" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#r-packages"><i class="fa fa-check"></i><b>1.2</b> R packages</a></li>
<li class="chapter" data-level="1.3" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#variables-vectors-and-data-frames-in-r"><i class="fa fa-check"></i><b>1.3</b> Variables, vectors and data frames in R</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#data-frames"><i class="fa fa-check"></i><b>1.3.1</b> Data frames</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#functions-in-r"><i class="fa fa-check"></i><b>1.4</b> Functions in R</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#useful-inbuilt-functions"><i class="fa fa-check"></i><b>1.4.1</b> Useful inbuilt functions</a></li>
<li class="chapter" data-level="1.4.2" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#custom-functions"><i class="fa fa-check"></i><b>1.4.2</b> Custom functions</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#basic-plotting-in-r"><i class="fa fa-check"></i><b>1.5</b> Basic plotting in R</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#scatter-plot"><i class="fa fa-check"></i><b>1.5.1</b> Scatter plot</a></li>
<li class="chapter" data-level="1.5.2" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#line-graph"><i class="fa fa-check"></i><b>1.5.2</b> Line graph</a></li>
<li class="chapter" data-level="1.5.3" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#combined-graph"><i class="fa fa-check"></i><b>1.5.3</b> Combined graph</a></li>
<li class="chapter" data-level="1.5.4" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#barplot"><i class="fa fa-check"></i><b>1.5.4</b> Barplot</a></li>
<li class="chapter" data-level="1.5.5" data-path="general-introduction-to-rrstudio.html"><a href="general-introduction-to-rrstudio.html#boxplots"><i class="fa fa-check"></i><b>1.5.5</b> Boxplots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html"><i class="fa fa-check"></i><b>2</b> Data wrangling and visualisation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#loading-and-saving-data"><i class="fa fa-check"></i><b>2.2</b> Loading and saving data</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#save-load-data-as-an-r-object"><i class="fa fa-check"></i><b>2.2.1</b> Save / load data as an R object</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#save-load-as-a-csv-file"><i class="fa fa-check"></i><b>2.2.2</b> Save / load as a CSV file</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#handling-excel-files"><i class="fa fa-check"></i><b>2.2.3</b> Handling Excel files</a></li>
<li class="chapter" data-level="2.2.4" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#cheatsheet"><i class="fa fa-check"></i><b>2.2.4</b> Cheatsheet</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#visualisation-using-ggplot"><i class="fa fa-check"></i><b>2.3</b> Visualisation using <code>ggplot</code></a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#aesthetics"><i class="fa fa-check"></i><b>2.3.1</b> Aesthetics</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#geoms"><i class="fa fa-check"></i><b>2.3.2</b> Geoms</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#labels"><i class="fa fa-check"></i><b>2.3.3</b> Labels</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#faceting"><i class="fa fa-check"></i><b>2.3.4</b> Faceting</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#statistical-transformation"><i class="fa fa-check"></i><b>2.3.5</b> Statistical transformation</a></li>
<li class="chapter" data-level="2.3.6" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#scales"><i class="fa fa-check"></i><b>2.3.6</b> Scales</a></li>
<li class="chapter" data-level="2.3.7" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#assigning-plots-to-objects"><i class="fa fa-check"></i><b>2.3.7</b> Assigning plots to objects</a></li>
<li class="chapter" data-level="2.3.8" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#putting-it-all-together"><i class="fa fa-check"></i><b>2.3.8</b> Putting it all together</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#data-wrangling"><i class="fa fa-check"></i><b>2.4</b> Data wrangling</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#tidy-data"><i class="fa fa-check"></i><b>2.4.1</b> Tidy data</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#filter-rows"><i class="fa fa-check"></i><b>2.4.2</b> Filter rows</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#sort-rows"><i class="fa fa-check"></i><b>2.4.3</b> Sort rows</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#select-columns"><i class="fa fa-check"></i><b>2.4.4</b> Select columns</a></li>
<li class="chapter" data-level="2.4.5" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#grouping-and-summarising"><i class="fa fa-check"></i><b>2.4.5</b> Grouping and summarising</a></li>
<li class="chapter" data-level="2.4.6" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#reshaping-datasets"><i class="fa fa-check"></i><b>2.4.6</b> Reshaping datasets</a></li>
<li class="chapter" data-level="2.4.7" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#mutate"><i class="fa fa-check"></i><b>2.4.7</b> Mutate</a></li>
<li class="chapter" data-level="2.4.8" data-path="data-wrangling-and-visualisation.html"><a href="data-wrangling-and-visualisation.html#dealing-with-missing-data"><i class="fa fa-check"></i><b>2.4.8</b> Dealing with missing data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html"><i class="fa fa-check"></i><b>3</b> Introduction to statistical modelling in R</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#what-is-a-statistical-model"><i class="fa fa-check"></i>What is a statistical model?</a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#descriptive-vs.-inferential-statistics"><i class="fa fa-check"></i>Descriptive vs. inferential statistics</a></li>
<li class="chapter" data-level="3.1" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#univariate-analysis"><i class="fa fa-check"></i><b>3.1</b> Univariate analysis</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#mean-vs.-median"><i class="fa fa-check"></i><strong>Mean vs. median</strong></a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#interquartile-range"><i class="fa fa-check"></i><strong>Interquartile range</strong></a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#skewness"><i class="fa fa-check"></i><strong>Skewness</strong></a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#kurtosis"><i class="fa fa-check"></i><strong>Kurtosis</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#multivariate-analysis"><i class="fa fa-check"></i><b>3.2</b> Multivariate analysis</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#contingency-tables"><i class="fa fa-check"></i><strong>Contingency tables</strong></a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#pearson-correlation"><i class="fa fa-check"></i><strong>Pearson correlation</strong></a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#spearmans-rank-correlation"><i class="fa fa-check"></i><strong>Spearman’s rank correlation</strong></a></li>
<li class="chapter" data-level="" data-path="introduction-to-statistical-modelling-in-r.html"><a href="introduction-to-statistical-modelling-in-r.html#correlation-vs.-causation"><i class="fa fa-check"></i><strong>Correlation vs. causation</strong></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="linear-models-lm.html"><a href="linear-models-lm.html"><i class="fa fa-check"></i><b>4</b> Linear Models (LM)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="linear-models-lm.html"><a href="linear-models-lm.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="4.2" data-path="linear-models-lm.html"><a href="linear-models-lm.html#linear-regression-in-r"><i class="fa fa-check"></i><b>4.2</b> Linear regression in R</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="linear-models-lm.html"><a href="linear-models-lm.html#using-the-summary-function"><i class="fa fa-check"></i><b>4.2.1</b> <strong>Using the <code>summary()</code> function</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="linear-models-lm.html"><a href="linear-models-lm.html#model-checking"><i class="fa fa-check"></i><b>4.3</b> Model checking</a>
<ul>
<li class="chapter" data-level="" data-path="linear-models-lm.html"><a href="linear-models-lm.html#residuals-vs-fitted"><i class="fa fa-check"></i><strong>Residuals vs Fitted</strong></a></li>
<li class="chapter" data-level="" data-path="linear-models-lm.html"><a href="linear-models-lm.html#normal-q-q"><i class="fa fa-check"></i><strong>Normal Q-Q</strong></a></li>
<li class="chapter" data-level="" data-path="linear-models-lm.html"><a href="linear-models-lm.html#scale-location"><i class="fa fa-check"></i><strong>Scale-Location</strong></a></li>
<li class="chapter" data-level="" data-path="linear-models-lm.html"><a href="linear-models-lm.html#residuals-vs-leverage"><i class="fa fa-check"></i><strong>Residuals vs Leverage</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="linear-models-lm.html"><a href="linear-models-lm.html#prediction"><i class="fa fa-check"></i><b>4.4</b> Prediction</a></li>
<li class="chapter" data-level="4.5" data-path="linear-models-lm.html"><a href="linear-models-lm.html#multiple-linear-regression"><i class="fa fa-check"></i><b>4.5</b> Multiple linear regression</a></li>
<li class="chapter" data-level="4.6" data-path="linear-models-lm.html"><a href="linear-models-lm.html#categorical-explanatory-variables"><i class="fa fa-check"></i><b>4.6</b> Categorical explanatory variables</a></li>
<li class="chapter" data-level="4.7" data-path="linear-models-lm.html"><a href="linear-models-lm.html#interactions"><i class="fa fa-check"></i><b>4.7</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="mixed-effect-models-mem.html"><a href="mixed-effect-models-mem.html"><i class="fa fa-check"></i><b>5</b> Mixed Effect Models (MEM)</a>
<ul>
<li class="chapter" data-level="5.1" data-path="mixed-effect-models-mem.html"><a href="mixed-effect-models-mem.html#model-checking-1"><i class="fa fa-check"></i><b>5.1</b> Model checking</a></li>
<li class="chapter" data-level="5.2" data-path="mixed-effect-models-mem.html"><a href="mixed-effect-models-mem.html#further-reading"><i class="fa fa-check"></i><b>5.2</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html"><i class="fa fa-check"></i><b>6</b> Generalised Linear Models (GLM)</a>
<ul>
<li class="chapter" data-level="6.1" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#link-functions"><i class="fa fa-check"></i><b>6.1</b> Link functions</a></li>
<li class="chapter" data-level="6.2" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#poisson-regression-for-count-data"><i class="fa fa-check"></i><b>6.2</b> Poisson regression (for count data)</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#background"><i class="fa fa-check"></i><b>6.2.1</b> Background</a></li>
<li class="chapter" data-level="6.2.2" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#poisson-regression-in-r"><i class="fa fa-check"></i><b>6.2.2</b> Poisson regression in R</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#logistic-regression-for-binary-data"><i class="fa fa-check"></i><b>6.3</b> Logistic regression (for binary data)</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#background-1"><i class="fa fa-check"></i><b>6.3.1</b> Background</a></li>
<li class="chapter" data-level="6.3.2" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#logistic-regression-in-r"><i class="fa fa-check"></i><b>6.3.2</b> Logistic regression in R</a></li>
<li class="chapter" data-level="" data-path="generalised-linear-models-glm.html"><a href="generalised-linear-models-glm.html#odds-ratios"><i class="fa fa-check"></i>Odds ratios</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="survival-analysis.html"><a href="survival-analysis.html"><i class="fa fa-check"></i><b>7</b> Survival Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="survival-analysis.html"><a href="survival-analysis.html#terminology-and-notation"><i class="fa fa-check"></i><b>7.1</b> Terminology and notation</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="survival-analysis.html"><a href="survival-analysis.html#censoring"><i class="fa fa-check"></i><b>7.1.1</b> Censoring</a></li>
<li class="chapter" data-level="7.1.2" data-path="survival-analysis.html"><a href="survival-analysis.html#survival-and-hazard-functions"><i class="fa fa-check"></i><b>7.1.2</b> Survival and hazard functions</a></li>
<li class="chapter" data-level="7.1.3" data-path="survival-analysis.html"><a href="survival-analysis.html#calculating-survival-times-in-r"><i class="fa fa-check"></i><b>7.1.3</b> Calculating survival times in R</a></li>
<li class="chapter" data-level="7.1.4" data-path="survival-analysis.html"><a href="survival-analysis.html#r-libraries-and-example-data"><i class="fa fa-check"></i><b>7.1.4</b> R libraries and example data</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="survival-analysis.html"><a href="survival-analysis.html#kaplan-meier"><i class="fa fa-check"></i><b>7.2</b> Kaplan-Meier</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="survival-analysis.html"><a href="survival-analysis.html#median-survival-time"><i class="fa fa-check"></i><b>7.2.1</b> <strong>Median survival time</strong></a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="survival-analysis.html"><a href="survival-analysis.html#cox-regression-model"><i class="fa fa-check"></i><b>7.3</b> Cox regression model</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to statistical data analysis in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-models-lm" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Linear Models (LM)<a href="linear-models-lm.html#linear-models-lm" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="simple-linear-regression" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Simple linear regression<a href="linear-models-lm.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When analysing data, we are often interested in exploring the relationship between a single response variable and one or multiple explanatory variables (predictors). This can be done by fitting a linear model. In fact, we have already come across this in earlier sections of this workshop; here we will provide more information on what is unde the hood and how to do perform linear modelling in R.</p>
<p>The term <em>linear</em> in linear models refers to the fact that there is a <em>linear</em>, or straight line, relationship between a predictor, <span class="math inline">\(x\)</span>, and the response <span class="math inline">\(y\)</span>. In other words, we can write
<span class="math display">\[ y = \beta_0 + \beta_1 x \]</span>
where <span class="math inline">\(\beta_0\)</span> is the so-called <em>intercept</em>, i.e. the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x=0\)</span>, and <span class="math inline">\(\beta_1\)</span> is the <em>gradient</em>, which describes by how much <span class="math inline">\(y\)</span> varies with increasing or decreasing values of <span class="math inline">\(x\)</span>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-144-1.png" style="display: block; margin: auto;" /></p>
<p>What can be seen form the above graph is that the data points are not all on top of the regression line but spread above and below it. What this means is that an individual data point, <span class="math inline">\(y_i\)</span>, can be described by the linear relationship
<span class="math display">\[y_i = \beta_0 + \beta_1 x_i + \epsilon_i\]</span>
where <span class="math inline">\(\epsilon_i\)</span> is the deviation, or (residual) error, between the best line fit and the actually observed value <span class="math inline">\(y_i\)</span>.</p>
<p>One on the key assumptions of a linear model is that all the <span class="math inline">\(\epsilon_i\)</span>’s are normally distributed with a mean of 0 and some standard deviation <span class="math inline">\(\sigma\)</span>. In mathematical terms, the linear regression model is therefore defined as
<span class="math display">\[
\begin{align}
y_i &amp;= \beta_0 + \beta_1 x_i + \epsilon_i \\
\epsilon_i &amp;\sim \mathcal{N}(0, \sigma^2)
\end{align}
\]</span></p>
<p><span class="math inline">\(\epsilon\)</span> is also commonly referred as the <strong>noise</strong> term. This is because the response variable has usually some uncertainty associated with it (e.g quantifying gene expression using microarrays or RNA-seq, etc.).</p>
<p>The general idea behind linear regression is to find the best fit line which minimises, or absorbs, the total (residual) noise. We are not going into the mathematical intricacies but rather show you how this is done in R, together with the general workflow of linear regression</p>
<ol style="list-style-type: decimal">
<li>infer the model parameters <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span></li>
<li>check the model fit</li>
<li>interpret the significance of the estimated parameters</li>
</ol>
</div>
<div id="linear-regression-in-r" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Linear regression in R<a href="linear-models-lm.html#linear-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To show you how easy it is to linear regression in R we first create a fake dataset, which contains data of the height and weight of <span class="math inline">\(N=100\)</span> individuals randomly sampled from a population</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="linear-models-lm.html#cb231-1" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb231-2"><a href="linear-models-lm.html#cb231-2" tabindex="-1"></a>height <span class="ot">&lt;-</span> <span class="fu">runif</span>(N, <span class="at">min =</span> <span class="dv">135</span>, <span class="at">max =</span> <span class="dv">195</span>)</span>
<span id="cb231-3"><a href="linear-models-lm.html#cb231-3" tabindex="-1"></a>weight <span class="ot">&lt;-</span> <span class="fl">0.48</span> <span class="sc">*</span> height <span class="sc">+</span> <span class="fu">rnorm</span>(N, <span class="at">mean=</span><span class="dv">0</span>, <span class="at">sd=</span><span class="dv">7</span>)</span>
<span id="cb231-4"><a href="linear-models-lm.html#cb231-4" tabindex="-1"></a></span>
<span id="cb231-5"><a href="linear-models-lm.html#cb231-5" tabindex="-1"></a>sampleData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">height =</span> height,</span>
<span id="cb231-6"><a href="linear-models-lm.html#cb231-6" tabindex="-1"></a>                         <span class="at">weight =</span> weight) </span>
<span id="cb231-7"><a href="linear-models-lm.html#cb231-7" tabindex="-1"></a></span>
<span id="cb231-8"><a href="linear-models-lm.html#cb231-8" tabindex="-1"></a><span class="fu">ggplot</span>(sampleData, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb231-9"><a href="linear-models-lm.html#cb231-9" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb231-10"><a href="linear-models-lm.html#cb231-10" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;height (cm)&#39;</span>,</span>
<span id="cb231-11"><a href="linear-models-lm.html#cb231-11" tabindex="-1"></a>         <span class="at">y =</span> <span class="st">&#39;weight (kg)&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-145-1.png" style="display: block; margin: auto;" /></p>
<p>Judging by eye we would be confident to declare that there is a (linear) relationship between the height and weight of an individual. So let’s fit a linear regression model and check whether this is indeed the case (in a statistical sense). To do this in R we will use the <code>lm()</code> function (please read the documentation for full details). This function requires a <strong>formular</strong> that describes the relationship between the predictor or explanatory variable (here height) and the response variable (here weight), which is given in the form <code>response ~ explanatory</code>, or in our case <code>weight ~ height</code>. With this, R will try to fit the following model
<span class="math display">\[ weight_i = \beta_0 + \beta_1 \times height_i + \epsilon_i \]</span></p>
<p>And here is how this is done</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="linear-models-lm.html#cb232-1" tabindex="-1"></a><span class="co"># fit linear model and assign to object &#39;fit&#39;</span></span>
<span id="cb232-2"><a href="linear-models-lm.html#cb232-2" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> height, <span class="at">data =</span> sampleData)</span>
<span id="cb232-3"><a href="linear-models-lm.html#cb232-3" tabindex="-1"></a></span>
<span id="cb232-4"><a href="linear-models-lm.html#cb232-4" tabindex="-1"></a><span class="co"># print output</span></span>
<span id="cb232-5"><a href="linear-models-lm.html#cb232-5" tabindex="-1"></a><span class="fu">print</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ height, data = sampleData)
## 
## Coefficients:
## (Intercept)       height  
##      8.8537       0.4204</code></pre>
<p>The output of interest are the two numbers <code>(Intercept)</code>= 8.8537, which is our <span class="math inline">\(\beta_0\)</span> term, and <code>weight</code>= 0.4204, which is our <span class="math inline">\(\beta_1\)</span> term.</p>
<p>So far so good; but how do we get the regression line? There are, in principle, two ways: either we calculate this by hand using the beta-terms we just obtained, or we use the <code>predict()</code> function (please see R documentation for further details).</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="linear-models-lm.html#cb234-1" tabindex="-1"></a><span class="co"># define the x-range for our regression line</span></span>
<span id="cb234-2"><a href="linear-models-lm.html#cb234-2" tabindex="-1"></a>bestFit <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">height =</span> <span class="fu">c</span>(<span class="dv">135</span>, <span class="dv">195</span>))</span>
<span id="cb234-3"><a href="linear-models-lm.html#cb234-3" tabindex="-1"></a></span>
<span id="cb234-4"><a href="linear-models-lm.html#cb234-4" tabindex="-1"></a><span class="co"># Option 1: calculate the y-values by hand</span></span>
<span id="cb234-5"><a href="linear-models-lm.html#cb234-5" tabindex="-1"></a>bestFit[<span class="st">&quot;weight&quot;</span>] <span class="ot">&lt;-</span> <span class="fl">5.0613</span> <span class="sc">+</span> <span class="fl">0.4471</span> <span class="sc">*</span> bestFit<span class="sc">$</span>height</span>
<span id="cb234-6"><a href="linear-models-lm.html#cb234-6" tabindex="-1"></a></span>
<span id="cb234-7"><a href="linear-models-lm.html#cb234-7" tabindex="-1"></a><span class="co"># Option 2: use the predict() function</span></span>
<span id="cb234-8"><a href="linear-models-lm.html#cb234-8" tabindex="-1"></a>bestFit[<span class="st">&quot;weight&quot;</span>] <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit, <span class="at">newdata =</span> bestFit)</span>
<span id="cb234-9"><a href="linear-models-lm.html#cb234-9" tabindex="-1"></a></span>
<span id="cb234-10"><a href="linear-models-lm.html#cb234-10" tabindex="-1"></a><span class="fu">ggplot</span>(sampleData, <span class="fu">aes</span>(<span class="at">x=</span>height, <span class="at">y=</span>weight)) <span class="sc">+</span></span>
<span id="cb234-11"><a href="linear-models-lm.html#cb234-11" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb234-12"><a href="linear-models-lm.html#cb234-12" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data=</span>bestFit, <span class="fu">aes</span>(<span class="at">x=</span>height, <span class="at">y=</span>weight), <span class="at">col =</span> <span class="st">&#39;blue&#39;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-147-1.png" style="display: block; margin: auto;" /></p>
<blockquote>
<p><strong>Note:</strong> this is essentially what <code>geom_smooth(method = 'lm')</code> would have done for us!</p>
</blockquote>
<div id="using-the-summary-function" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> <strong>Using the <code>summary()</code> function</strong><a href="linear-models-lm.html#using-the-summary-function" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Above the called <code>print(fit)</code> to obtain the fitted parameters of our model. However, if you check carefully in the <em>Environment</em> tab in RStudio, you will see that <code>fit</code> contains a lot more information. And this can be summarised in a much more informative fashion using the <code>summary()</code> function</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="linear-models-lm.html#cb235-1" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ height, data = sampleData)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -13.2130  -5.0512  -0.6079   4.6114  24.7020 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  8.85369    7.45411   1.188    0.238    
## height       0.42043    0.04554   9.232 5.63e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.234 on 98 degrees of freedom
## Multiple R-squared:  0.4651, Adjusted R-squared:  0.4597 
## F-statistic: 85.23 on 1 and 98 DF,  p-value: 5.627e-15</code></pre>
<p>Let’s go through this line-by-line</p>
<ul>
<li><p><strong>Call</strong> <br>
This just states the arguments that were passed to the <code>lm()</code> function. Remember it’s <code>response ~ explanatory</code>.</p></li>
<li><p><strong>Residuals</strong> <br>
Some basic stats about the residuals (i.e the differences between the model fit and the observed data points). It is easier to plot a histogram of the residuals (shown in the next section), but these basic stats can already give us an indication of whether we have a symmetric distribution with zero mean (i.e we want the median to be close to zero, the third quartile (Q3) to be roughly equal to -Q1 (first quartile) and the max to be approximately -min).</p></li>
<li><p><strong>Coefficients</strong> <br></p>
<ul>
<li><p><code>Estimate</code> <br>
<code>(Intercept)</code>= 8.8537 and <code>weight</code>= 0.4204 kg/cm are our regression parameters.</p></li>
<li><p><code>Std. Error</code> <br>
The standard errors for the two inferred parameters. They tells us how confident we are in our estimates: if the standard error is comparable or greater than the actual parameter estimate itself then that point estimate should not be trusted. We can also show the confidence intervals for the model parameters to highlight their uncertainty using the <code>confint()</code> function:</p></li>
</ul>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="linear-models-lm.html#cb237-1" tabindex="-1"></a><span class="fu">confint</span>(fit, <span class="at">levels=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                 2.5 %    97.5 %
## (Intercept) -5.938749 23.646134
## height       0.330056  0.510808</code></pre>
<ul>
<li><code>t value</code> and <code>Pr(&gt;|t|)</code> <br>
This is the result of a hypothesis testing against the null hypothesis that the coefficient is zero.</li>
</ul></li>
<li><p><strong>Residual standard error</strong> <br>
The square root of the residual sum of squares / degrees of freedom (here 98 = 100 (data points) - 2 (parameters needed for the regression line))</p></li>
<li><p><strong>Multiple R-squared</strong> <br>
The <span class="math inline">\(R^2\)</span> statistic, which is also referred to as as the coefficient of determination is the proportion of the total variation that is explained by the regression, i.e. <br></p>
<center>
<p><strong>total variation</strong> = <strong>regression</strong> (explained) variation + <strong>residual</strong> (unexplained) variation</p>
</center>
<p><br>
In regression with a single explanatory variable, this is the same as the Pearson correlation coefficient squared.</p></li>
<li><p><strong>F-statistic</strong> <br>
The F-statistic can be used to assess whether the amount of variation explained by the regression (<span class="math inline">\(M_1\)</span>) is statistically significantly different compared to the null model (<span class="math inline">\(M_0\)</span>), which in this case corresponds just taking the mean of the data. Large values of the F-statistic correspond to cases where the model fit is better for the more complex model compared to the null model. This test can be used to generate a P-value to assess whether the model fit is statistically significantly better given a pre-defined level of significance.</p></li>
</ul>
</div>
</div>
<div id="model-checking" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Model checking<a href="linear-models-lm.html#model-checking" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The next step in linear (or any statistical) modelling is the concept of <strong>model checking</strong>. In theory, we could fit any model to our data simply by changing our assumptions about how the response and predictor variables are related. What we would like to do, however, is to make <strong>robust</strong> inferences, and for this we must check our model, which essentially boils down to checking whether our assumptions are reasonable.</p>
<p>The main assumption in our model was that the residuals (the differences between the data points and the regression line) are normally distributed around 0. We can easily check whether this is the case</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="linear-models-lm.html#cb239-1" tabindex="-1"></a><span class="fu">hist</span>(fit<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-150-1.png" style="display: block; margin: auto;" /></p>
<p>We can see that the residuals are fairly evenly distributed and centered around 0, which is a good sign!</p>
<p>R also provides us with some easy tools for further model diagnostics, which can be called simply through</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="linear-models-lm.html#cb240-1" tabindex="-1"></a><span class="co">#setting up a 2x2 plot grid</span></span>
<span id="cb240-2"><a href="linear-models-lm.html#cb240-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb240-3"><a href="linear-models-lm.html#cb240-3" tabindex="-1"></a></span>
<span id="cb240-4"><a href="linear-models-lm.html#cb240-4" tabindex="-1"></a><span class="co"># plot model diagnostics</span></span>
<span id="cb240-5"><a href="linear-models-lm.html#cb240-5" tabindex="-1"></a><span class="fu">plot</span>(fit, <span class="at">pch =</span> <span class="dv">20</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-151-1.png" style="display: block; margin: auto;" />
What do these plot tell us about the model fit, though?</p>
<div id="residuals-vs-fitted" class="section level3 unnumbered hasAnchor">
<h3><strong>Residuals vs Fitted</strong><a href="linear-models-lm.html#residuals-vs-fitted" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The first plot, <em>Residuals vs Fitted</em>, checks that the variance is constant along the fitted line and that there is no systematic pattern whereby the errors get bigger or smaller as dependent on the fitted values. In our case, everything seems to be OK, but here are some (extreme) examples where this is not the case:</p>
<p><img src="images/02-funnel.png" width="600px" style="display: block; margin: auto;" /></p>
</div>
<div id="normal-q-q" class="section level3 unnumbered hasAnchor">
<h3><strong>Normal Q-Q</strong><a href="linear-models-lm.html#normal-q-q" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A Q–Q plot, or <em>quantile-quantile</em> plot, compares two probability distributions by plotting their quantiles against each other. If the two distributions are similar, then the points should fall approximately on the identity line <span class="math inline">\(y = x\)</span>. In our case, we are plotting the quantiles of the residuals against their <em>assumed</em> distribution, which is the Normal distribution, and see that there is nothing to worry about (which we should know already from the histogram above).</p>
<p>Here is an example when things go wrong (i.e. when our linear assumption is violated):</p>
<p><img src="_main_files/figure-html/unnamed-chunk-153-1.png" style="display: block; margin: auto;" /></p>
</div>
<div id="scale-location" class="section level3 unnumbered hasAnchor">
<h3><strong>Scale-Location</strong><a href="linear-models-lm.html#scale-location" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The scale location graph is very similar to the first plot but on a different scale.</p>
</div>
<div id="residuals-vs-leverage" class="section level3 unnumbered hasAnchor">
<h3><strong>Residuals vs Leverage</strong><a href="linear-models-lm.html#residuals-vs-leverage" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The last plot examines the influence of individual data points on our inference. Ideally, all points should equally contribute to the fit. In some cases we might find outliers, which have an above <em>leverage</em> on the fitted line, which can be measured by *Cook’s distance’. An extreme example is shown here</p>
<p><img src="_main_files/figure-html/unnamed-chunk-154-1.png" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="prediction" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Prediction<a href="linear-models-lm.html#prediction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Making predictions about unknown or unobserved data is the key benefit of statistical modelling. In fact, we have already used this to overlay a regression line onto our data by using the <code>predict()</code> function. Going back to our original example, let’s say we want to know the <em>average</em> weight for an individual who is 187cm tall. Note, the <code>predict()</code> function requires the new (to be predicted) data to be provided as a data.frame.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="linear-models-lm.html#cb241-1" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">height=</span><span class="dv">187</span>))</span></code></pre></div>
<pre><code>##        1 
## 87.47447</code></pre>
<p>Remember that our inference comes with a degree of uncertainties (because we can never know the true relationship based on a random sample from a population). A useful feature of the <code>predict()</code> function is that it can not only provide point estimates but also the <strong>confidence</strong> or <strong>prediction</strong> interval. Let’ say we are intereted in the 95% confidence interval for our prediction</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="linear-models-lm.html#cb243-1" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">height=</span><span class="dv">187</span>), <span class="at">interval =</span> <span class="st">&#39;confidence&#39;</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 87.47447 84.86624 90.08271</code></pre>
<p>and to obtain the 96% prediction interval</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="linear-models-lm.html#cb245-1" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="fu">data.frame</span>(<span class="at">height=</span><span class="dv">187</span>), <span class="at">interval =</span> <span class="st">&#39;prediction&#39;</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 87.47447 72.88477 102.0642</code></pre>
<p>As you can see, the prediction interval is significantly larger than the confidence interval.</p>
<div id="confidence-vs-prediction-interval" class="section level4 hasAnchor" number="4.4.0.1">
<h4><span class="header-section-number">4.4.0.1</span> <strong>Confidence vs prediction interval</strong><a href="linear-models-lm.html#confidence-vs-prediction-interval" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <em>confidence interval</em> corresponds to the uncertainty surrounding our estimate of an <strong>average individual</strong>; it represents the uncertainty in the mean (i.e. in our case the regression line): <span class="math inline">\(y = \beta_0 + \beta_1 x\)</span>. In contrast, the <em>prediction interval</em> corresponds to the uncertainty surrounding an <strong>Individual observation</strong>.</p>
<p>Here we show you how both intervals can be computed and added to your (linear) regression line. Although these are often not shown they are important for conveying uncertainties.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="linear-models-lm.html#cb247-1" tabindex="-1"></a>newheight <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">height =</span> <span class="fu">seq</span>(<span class="fu">min</span>(sampleData<span class="sc">$</span>height), <span class="fu">max</span>(sampleData<span class="sc">$</span>height), <span class="at">length.out=</span><span class="dv">100</span>))</span>
<span id="cb247-2"><a href="linear-models-lm.html#cb247-2" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newheight, <span class="fu">predict</span>(fit, <span class="at">newdata =</span> newheight, <span class="at">interval =</span> <span class="st">&#39;confidence&#39;</span>, <span class="at">level =</span> <span class="fl">0.95</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb247-3"><a href="linear-models-lm.html#cb247-3" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">weight =</span> fit)</span>
<span id="cb247-4"><a href="linear-models-lm.html#cb247-4" tabindex="-1"></a></span>
<span id="cb247-5"><a href="linear-models-lm.html#cb247-5" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb247-6"><a href="linear-models-lm.html#cb247-6" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> sampleData) <span class="sc">+</span></span>
<span id="cb247-7"><a href="linear-models-lm.html#cb247-7" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">data =</span> newdata, <span class="fu">aes</span>(<span class="at">ymin=</span>lwr, <span class="at">ymax=</span>upr), <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb247-8"><a href="linear-models-lm.html#cb247-8" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data =</span> newdata, <span class="at">col =</span> <span class="st">&#39;blue&#39;</span>, <span class="at">linewidth=</span><span class="dv">1</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-158-1.png" style="display: block; margin: auto;" /></p>
<p>… and now compare this to what <code>geom_smooth()</code> produces</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="linear-models-lm.html#cb248-1" tabindex="-1"></a><span class="fu">ggplot</span>(sampleData, <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb248-2"><a href="linear-models-lm.html#cb248-2" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb248-3"><a href="linear-models-lm.html#cb248-3" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-159-1.png" style="display: block; margin: auto;" /></p>
<p>They are the same - so now you know what <code>geom_smooth()</code> actually does!</p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Produce a similar graph but now plot the 97% prediction interval instead of the confidence interval. Can you put them both in the same graph?
</div>
</div>
<button id="displayTextunnamed-chunk-161" onclick="javascript:toggle(&#39;unnamed-chunk-161&#39;);">
Show: Solution
</button>
<div id="toggleTextunnamed-chunk-161" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="linear-models-lm.html#cb249-1" tabindex="-1"></a>newheight <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">height =</span> <span class="fu">seq</span>(<span class="fu">min</span>(sampleData<span class="sc">$</span>height), <span class="fu">max</span>(sampleData<span class="sc">$</span>height), <span class="at">length.out=</span><span class="dv">100</span>))</span>
<span id="cb249-2"><a href="linear-models-lm.html#cb249-2" tabindex="-1"></a>newdata_ci <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newheight, <span class="fu">predict</span>(fit, <span class="at">newdata =</span> newheight, <span class="at">interval =</span> <span class="st">&#39;confidence&#39;</span>, <span class="at">level =</span> <span class="fl">0.97</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb249-3"><a href="linear-models-lm.html#cb249-3" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">weight =</span> fit)</span>
<span id="cb249-4"><a href="linear-models-lm.html#cb249-4" tabindex="-1"></a>newdata_pi <span class="ot">&lt;-</span> <span class="fu">cbind</span>(newheight, <span class="fu">predict</span>(fit, <span class="at">newdata =</span> newheight, <span class="at">interval =</span> <span class="st">&#39;prediction&#39;</span>, <span class="at">level =</span> <span class="fl">0.97</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb249-5"><a href="linear-models-lm.html#cb249-5" tabindex="-1"></a>    <span class="fu">rename</span>(<span class="at">weight =</span> fit)</span>
<span id="cb249-6"><a href="linear-models-lm.html#cb249-6" tabindex="-1"></a></span>
<span id="cb249-7"><a href="linear-models-lm.html#cb249-7" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> height, <span class="at">y =</span> weight)) <span class="sc">+</span></span>
<span id="cb249-8"><a href="linear-models-lm.html#cb249-8" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> sampleData) <span class="sc">+</span></span>
<span id="cb249-9"><a href="linear-models-lm.html#cb249-9" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">data =</span> newdata_pi, <span class="fu">aes</span>(<span class="at">ymin=</span>lwr, <span class="at">ymax=</span>upr), <span class="at">fill =</span> <span class="st">&#39;grey&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb249-10"><a href="linear-models-lm.html#cb249-10" tabindex="-1"></a>    <span class="fu">geom_ribbon</span>(<span class="at">data =</span> newdata_ci, <span class="fu">aes</span>(<span class="at">ymin=</span>lwr, <span class="at">ymax=</span>upr), <span class="at">fill =</span> <span class="st">&#39;red&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb249-11"><a href="linear-models-lm.html#cb249-11" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data =</span> newdata_ci, <span class="at">col =</span> <span class="st">&#39;blue&#39;</span>, <span class="at">linewidth=</span><span class="dv">1</span>) </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-476-1.png" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<p><span class="math inline">\(~\)</span></p>
</div>
</div>
<div id="multiple-linear-regression" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Multiple linear regression<a href="linear-models-lm.html#multiple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far we have only considered a single explanatory variable, for example <em>height</em>. In most scenarios, however, we will have measured more than variable that could affect the outcome (response). In this case, our linear regression model extends to
<span class="math display">\[ y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + ... + \beta_n x_{ni} + \epsilon_i \]</span></p>
Let’s make up some artificial data again to illustrate how to perform multiple linear regression in R. In this case we assume we had measure the total number of malaria episodes of 100 individuals aged between 1 and 10 living under different transmission intensities, measured as EIR and here for simplicity scaled to between 0 and 1. The model we are therefore trying to fit is
<center>
episodes<span class="math inline">\(_i\)</span> = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span>EIR<span class="math inline">\(_i\)</span> + <span class="math inline">\(\beta_2\)</span>age<span class="math inline">\(_i\)</span>
</center>
<p>First, create our new dataset</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="linear-models-lm.html#cb250-1" tabindex="-1"></a><span class="co"># create random data points for age and EIR</span></span>
<span id="cb250-2"><a href="linear-models-lm.html#cb250-2" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">1</span>, <span class="dv">10</span>)</span>
<span id="cb250-3"><a href="linear-models-lm.html#cb250-3" tabindex="-1"></a>EIR <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb250-4"><a href="linear-models-lm.html#cb250-4" tabindex="-1"></a></span>
<span id="cb250-5"><a href="linear-models-lm.html#cb250-5" tabindex="-1"></a><span class="co"># assume some linear relationship between episodes and age and EIR plus noise</span></span>
<span id="cb250-6"><a href="linear-models-lm.html#cb250-6" tabindex="-1"></a>episodes <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fl">1.5</span><span class="sc">*</span>age <span class="sc">+</span> <span class="fl">4.1</span><span class="sc">*</span>EIR <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">2</span>))</span>
<span id="cb250-7"><a href="linear-models-lm.html#cb250-7" tabindex="-1"></a></span>
<span id="cb250-8"><a href="linear-models-lm.html#cb250-8" tabindex="-1"></a><span class="co"># put into new data.frame</span></span>
<span id="cb250-9"><a href="linear-models-lm.html#cb250-9" tabindex="-1"></a>epiData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Age =</span> age, <span class="at">Episodes =</span> episodes, <span class="at">EIR =</span> EIR)</span></code></pre></div>
<p>As a 3D-scatterplot this looks like this</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="linear-models-lm.html#cb251-1" tabindex="-1"></a><span class="fu">library</span>(scatterplot3d)</span>
<span id="cb251-2"><a href="linear-models-lm.html#cb251-2" tabindex="-1"></a><span class="fu">scatterplot3d</span>(EIR, age, episodes, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">ylab=</span><span class="st">&#39;Age (years)&#39;</span>, </span>
<span id="cb251-3"><a href="linear-models-lm.html#cb251-3" tabindex="-1"></a>              <span class="at">xlab=</span><span class="st">&#39;Transmission intensity&#39;</span>, <span class="at">zlab=</span><span class="st">&#39;Malaria episodes&#39;</span>, <span class="at">color=</span><span class="st">&#39;grey&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-163-1.png" style="display: block; margin: auto;" />
Note how we now spread our data along a third dimension, i.e. we go from 2D to 3D and from a best fit line to a best fit hyperplane. Adding more explanatory variables will effectively spread the data even further in more dimensions, which makes it much harder to make robust inferences. Another key objective in statistical modelling is therefore to find the <em>minimal adequate model</em>.</p>
<p>To fit the model in R we use exactly the same function and terminology as before</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="linear-models-lm.html#cb252-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(Episodes <span class="sc">~</span> EIR <span class="sc">+</span> Age, <span class="at">data =</span> epiData)</span></code></pre></div>
<p>which we can project onto our 3D-scatterplot</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="linear-models-lm.html#cb253-1" tabindex="-1"></a>hfig <span class="ot">&lt;-</span> <span class="fu">scatterplot3d</span>(EIR, age, episodes, <span class="at">pch=</span><span class="dv">19</span>, <span class="at">ylab=</span><span class="st">&#39;Age (years)&#39;</span>, </span>
<span id="cb253-2"><a href="linear-models-lm.html#cb253-2" tabindex="-1"></a>              <span class="at">xlab=</span><span class="st">&#39;Transmission intensity&#39;</span>, <span class="at">zlab=</span><span class="st">&#39;Malaria episodes&#39;</span>, <span class="at">color=</span><span class="st">&#39;grey&#39;</span>)</span>
<span id="cb253-3"><a href="linear-models-lm.html#cb253-3" tabindex="-1"></a>hfig<span class="sc">$</span><span class="fu">plane3d</span>(fit, <span class="at">draw_polygon=</span>T)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-165-1.png" style="display: block; margin: auto;" /></p>
<p>Next we are interested in the actual inference, i.e. the estimated parameters and some indication whether the two predictor variables (age and EIR) have a significant effect on the response (malaria episodes)</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="linear-models-lm.html#cb254-1" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Episodes ~ EIR + Age, data = epiData)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.2073 -1.4295 -0.2354  1.2642  5.4162 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.15704    0.63964   0.246    0.807    
## EIR          3.59941    0.71582   5.028 2.27e-06 ***
## Age          1.48781    0.08412  17.686  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.053 on 97 degrees of freedom
## Multiple R-squared:  0.7746, Adjusted R-squared:   0.77 
## F-statistic: 166.7 on 2 and 97 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As before, using the <code>summary()</code> function we get a summary of everything that’s important.</p>
<ul>
<li>the residuals appear symmetric and centered around 0</li>
<li>the estimates for <span class="math inline">\(\beta_1\)</span> (EIR) and <span class="math inline">\(\beta_2\)</span> (age) are both positive and in magnitude as expected</li>
<li>the estimate for <span class="math inline">\(\beta_0\)</span> is <span class="math inline">\(\neq 0\)</span> - what does this mean in practical terms? (we will revisit this at a later part of this workshop)</li>
<li>the inferred effects of both EIR and age are statistically significant</li>
<li>the adjusted R-squared value suggests that <span class="math inline">\(\sim 80\)</span>% of the variation is explained by our model</li>
</ul>
<p>This all seems really good, but we should still have a look at model diagnostics to see whether our model, or rather its underlying assumptions are valid.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="linear-models-lm.html#cb256-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb256-2"><a href="linear-models-lm.html#cb256-2" tabindex="-1"></a><span class="fu">plot</span>(fit)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-167-1.png" style="display: block; margin: auto;" /></p>
<p>The diagnostics all look reasonable and there is nothing that should make us doubt our model and assumed relationship between the response and explanatory variables. Note, these plots look exactly the same as in the simple linear model we have done earlier. This is because no matter how many (linear) predictors we put into our model, it is the behaviour of the residuals that we are interested in to make a statement about our model fit.</p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">

<ol style="list-style-type: decimal">
<li><p>Calculate the predicted number of episodes plus 95% cofidence intervals for a 5 year old living in a transmission setting with EIR=0.5</p></li>
<li><p>Fit a new model <code>Episodes ~ Age</code>. Look at the total variation explained and compare this to the full model; what would you conclude from this?</p></li>
<li><p>Fit a new model <code>Episodes ~ EIR</code>. Look at the estimate for the predictor variable and its associated P value and compare this to the ones based on the full model; what would you conclude from this?</p>
</div>
</div></li>
</ol>
<button id="displayTextunnamed-chunk-169" onclick="javascript:toggle(&#39;unnamed-chunk-169&#39;);">
Show: Solution
</button>
<div id="toggleTextunnamed-chunk-169" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="linear-models-lm.html#cb257-1" tabindex="-1"></a><span class="fu">predict</span>(fit, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">Age=</span><span class="dv">5</span>, <span class="at">EIR=</span><span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>##        1 
## 9.395781</code></pre>
</div>
</div>
</div>
<p><br></p>
</div>
<div id="categorical-explanatory-variables" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Categorical explanatory variables<a href="linear-models-lm.html#categorical-explanatory-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far we have only dealt with numerical predictor variables. But what about non-numerical or categorical variables? Turns out that these are as easily dealt with as numerical one. To show how to perform linear regression with one or more categorical explanatory variables, we slightly modify our malaria episode dataset to include one extra variable: bednet, which will be an indicator of whether the child sleeps under a bednet or not.</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="linear-models-lm.html#cb259-1" tabindex="-1"></a><span class="co"># create random data points for age and EIR</span></span>
<span id="cb259-2"><a href="linear-models-lm.html#cb259-2" tabindex="-1"></a>bednet <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&#39;yes&#39;</span>, <span class="st">&#39;no&#39;</span>), <span class="dv">100</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb259-3"><a href="linear-models-lm.html#cb259-3" tabindex="-1"></a></span>
<span id="cb259-4"><a href="linear-models-lm.html#cb259-4" tabindex="-1"></a><span class="co"># assume some linear relationship between episodes and age and EIR plus noise</span></span>
<span id="cb259-5"><a href="linear-models-lm.html#cb259-5" tabindex="-1"></a>episodes <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(bednet<span class="sc">==</span><span class="st">&#39;yes&#39;</span>, <span class="dv">0</span>, <span class="dv">2</span>) <span class="sc">+</span> <span class="fl">1.5</span><span class="sc">*</span>age <span class="sc">+</span> <span class="fl">4.1</span><span class="sc">*</span>EIR <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">2</span>)</span>
<span id="cb259-6"><a href="linear-models-lm.html#cb259-6" tabindex="-1"></a></span>
<span id="cb259-7"><a href="linear-models-lm.html#cb259-7" tabindex="-1"></a><span class="co"># put into new data.frame</span></span>
<span id="cb259-8"><a href="linear-models-lm.html#cb259-8" tabindex="-1"></a>epiData <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Episodes =</span> episodes, </span>
<span id="cb259-9"><a href="linear-models-lm.html#cb259-9" tabindex="-1"></a>                      <span class="at">Age =</span> age, </span>
<span id="cb259-10"><a href="linear-models-lm.html#cb259-10" tabindex="-1"></a>                      <span class="at">EIR =</span> EIR,</span>
<span id="cb259-11"><a href="linear-models-lm.html#cb259-11" tabindex="-1"></a>                      <span class="at">Bednet =</span> <span class="fu">factor</span>(bednet))</span></code></pre></div>
<p>The model we are fitting now looks very similar to the one we fitted before</p>
<center>
episodes<span class="math inline">\(_i\)</span> = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span>EIR<span class="math inline">\(_i\)</span> + <span class="math inline">\(\beta_2\)</span>age<span class="math inline">\(_i\)</span> + <span class="math inline">\(\beta_3\)</span>bednet<span class="math inline">\(_i\)</span>
</center>
<p><br></p>
<p>However, <em>bednet</em> is now a <em>dummy variable</em> that takes on a value of 0 (bednet = “no”) or 1 (bednet = “yes”). So essentially we are fitting <strong>two</strong> regression lines, one for those who sleep under a bednet and one for those who do not (because the <span class="math inline">\(\beta_3\)</span> term will fall out).</p>
<p>In terms of fitting this model in R, nothing has changed and we do not need to explicitly specify if one or more of the variables is a categorical one, the <code>lm()</code> function will take care of this for us</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="linear-models-lm.html#cb260-1" tabindex="-1"></a>fitCat <span class="ot">&lt;-</span> <span class="fu">lm</span>(Episodes <span class="sc">~</span> EIR <span class="sc">+</span> Age <span class="sc">+</span> Bednet, <span class="at">data =</span> epiData)</span>
<span id="cb260-2"><a href="linear-models-lm.html#cb260-2" tabindex="-1"></a><span class="fu">summary</span>(fitCat)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Episodes ~ EIR + Age + Bednet, data = epiData)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.379 -1.280  0.090  1.038  5.435 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.03776    0.57523   3.543 0.000614 ***
## EIR          4.68344    0.63706   7.352 6.52e-11 ***
## Age          1.54715    0.07706  20.076  &lt; 2e-16 ***
## Bednetyes   -3.26666    0.37840  -8.633 1.28e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.825 on 96 degrees of freedom
## Multiple R-squared:  0.8272, Adjusted R-squared:  0.8218 
## F-statistic: 153.1 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As you will notice from the summary, we now get an estimate for <code>Bednetyes</code> but not for <code>Bednetno</code>, what is going on? Becauase <code>Bednet</code> can only take on two values (0/1 or no/yes), one is taken as the <em>reference case</em>. That is, the intercept can now be interpreted as the average number of episodes for 0-year old living in a setting with an EIR=0. The estimate <code>Bednetyes</code>=-3.2667 tells you how much lower the expected number of episodes is for those who do sleep under a bednet.</p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Without using the <code>predict()</code> function, what is the predicted number of episodes for a 7-year old who sleeps under a bednet in a setting with an EIR of 0.8?
</div>
</div>
<button id="displayTextunnamed-chunk-173" onclick="javascript:toggle(&#39;unnamed-chunk-173&#39;);">
Show: Solution
</button>
<div id="toggleTextunnamed-chunk-173" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>This can be calculated as</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="linear-models-lm.html#cb262-1" tabindex="-1"></a>fitCat<span class="sc">$</span>coefficients[[<span class="dv">1</span>]] <span class="sc">+</span> fitCat<span class="sc">$</span>coefficients[[<span class="dv">2</span>]]<span class="sc">*</span><span class="fl">0.8</span> <span class="sc">+</span> fitCat<span class="sc">$</span>coefficients[[<span class="dv">3</span>]]<span class="sc">*</span><span class="dv">7</span> <span class="sc">+</span> fitCat<span class="sc">$</span>coefficients[[<span class="dv">4</span>]]</span></code></pre></div>
<pre><code>## [1] 13.34791</code></pre>
</div>
</div>
</div>
<p><br></p>
<p>To show the effect of the extra categorical variable, we can plot the data once by ignoring the effect of <code>Bednet</code> and once by colouring in the data points by bednet use.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="linear-models-lm.html#cb264-1" tabindex="-1"></a><span class="co"># very useful package for arranging multiple ggplots</span></span>
<span id="cb264-2"><a href="linear-models-lm.html#cb264-2" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb264-3"><a href="linear-models-lm.html#cb264-3" tabindex="-1"></a></span>
<span id="cb264-4"><a href="linear-models-lm.html#cb264-4" tabindex="-1"></a><span class="co"># simply plot all data and ignore the effect of bednet use</span></span>
<span id="cb264-5"><a href="linear-models-lm.html#cb264-5" tabindex="-1"></a><span class="co"># the lm function in this case would fit the model episodes ~ age + EIR</span></span>
<span id="cb264-6"><a href="linear-models-lm.html#cb264-6" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(epiData, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Episodes)) <span class="sc">+</span></span>
<span id="cb264-7"><a href="linear-models-lm.html#cb264-7" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb264-8"><a href="linear-models-lm.html#cb264-8" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&#39;lm&#39;</span>, <span class="at">se=</span>F)</span>
<span id="cb264-9"><a href="linear-models-lm.html#cb264-9" tabindex="-1"></a></span>
<span id="cb264-10"><a href="linear-models-lm.html#cb264-10" tabindex="-1"></a><span class="co"># create new dataset for predict()</span></span>
<span id="cb264-11"><a href="linear-models-lm.html#cb264-11" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb264-12"><a href="linear-models-lm.html#cb264-12" tabindex="-1"></a>    <span class="at">Age =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="at">length.out =</span> <span class="dv">10</span>),</span>
<span id="cb264-13"><a href="linear-models-lm.html#cb264-13" tabindex="-1"></a>    <span class="at">EIR =</span> <span class="fu">rep</span>(<span class="fu">median</span>(epiData<span class="sc">$</span>EIR), <span class="dv">10</span>),</span>
<span id="cb264-14"><a href="linear-models-lm.html#cb264-14" tabindex="-1"></a>    <span class="at">Bednet =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>)))</span>
<span id="cb264-15"><a href="linear-models-lm.html#cb264-15" tabindex="-1"></a></span>
<span id="cb264-16"><a href="linear-models-lm.html#cb264-16" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> newdata <span class="sc">%&gt;%</span> </span>
<span id="cb264-17"><a href="linear-models-lm.html#cb264-17" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Episodes =</span> <span class="fu">predict</span>(fitCat, newdata))</span>
<span id="cb264-18"><a href="linear-models-lm.html#cb264-18" tabindex="-1"></a></span>
<span id="cb264-19"><a href="linear-models-lm.html#cb264-19" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Episodes, <span class="at">col =</span> Bednet)) <span class="sc">+</span></span>
<span id="cb264-20"><a href="linear-models-lm.html#cb264-20" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">data =</span> epiData) <span class="sc">+</span></span>
<span id="cb264-21"><a href="linear-models-lm.html#cb264-21" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="at">data =</span> newdata, <span class="at">linewidth=</span><span class="dv">1</span>)</span>
<span id="cb264-22"><a href="linear-models-lm.html#cb264-22" tabindex="-1"></a></span>
<span id="cb264-23"><a href="linear-models-lm.html#cb264-23" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-174-1.png" style="display: block; margin: auto;" /></p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Use <code>ggplot</code> to plot <code>Episodes</code> against <code>Age</code> stratified (coloured) by <code>Bednet</code> and add regression lines using <code>geom_smooth(method = 'lm')</code>. What do you notice?
</div>
</div>
<button id="displayTextunnamed-chunk-176" onclick="javascript:toggle(&#39;unnamed-chunk-176&#39;);">
Show: Solution
</button>
<div id="toggleTextunnamed-chunk-176" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="linear-models-lm.html#cb265-1" tabindex="-1"></a><span class="fu">ggplot</span>(epiData, <span class="fu">aes</span>(<span class="at">x =</span> Age, <span class="at">y =</span> Episodes, <span class="at">col =</span> Bednet)) <span class="sc">+</span></span>
<span id="cb265-2"><a href="linear-models-lm.html#cb265-2" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb265-3"><a href="linear-models-lm.html#cb265-3" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>, <span class="at">se=</span>F)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-503-1.png" style="display: block; margin: auto;" /></p>
This graph looks very different to the one we preduced earlier. Although it still shows higher incidence for individuals without bednets, it suggests that the slopes are different (i.e. dependent on bednet use). Why this might be is subject of the next part dealing with interactions between predictor variables.
</div>
</div>
</div>
<p><br></p>
</div>
<div id="interactions" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Interactions<a href="linear-models-lm.html#interactions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before we go on to the next big topics, <em>Mixed Effect Models</em> and <em>Generalised Linear Models</em>, we briefly show you how to consider possible interactions between two or more variables. That is, we have so far considered that the different predictors (e.g. age and EIR) had an independent effect on the response variable (e.g. episodes). There are situations where this is not the case and where the effect of one explanatory variable on the response depends on the value of another explanatory variable. We can estimate this dependency by including a so-called <em>interaction term</em> in our model.</p>
<p>To illustrate the importance of interactions and how to deal with them in our regression model, we will look at an example where our inferences can be very misleading when not accounting for possible interaction effects.</p>
<p>Let’s consider another made up example, in this case a disease, which we believe is influenced by temperature and rainfall. Furthermore, let’s assume rainfall is seasonal but temperature is not, such that rainfall can be represented as a categorical variable; the response variable will be disease incidence.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="linear-models-lm.html#cb266-1" tabindex="-1"></a><span class="co"># create temperature and rinafall data</span></span>
<span id="cb266-2"><a href="linear-models-lm.html#cb266-2" tabindex="-1"></a>temperature <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>, <span class="dv">28</span>, <span class="dv">34</span>)</span>
<span id="cb266-3"><a href="linear-models-lm.html#cb266-3" tabindex="-1"></a>rainfall <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&#39;no&#39;</span>, <span class="st">&#39;yes&#39;</span>), <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb266-4"><a href="linear-models-lm.html#cb266-4" tabindex="-1"></a></span>
<span id="cb266-5"><a href="linear-models-lm.html#cb266-5" tabindex="-1"></a><span class="co"># define incidence as dependent on temperature, more so in rainy season </span></span>
<span id="cb266-6"><a href="linear-models-lm.html#cb266-6" tabindex="-1"></a>incidence <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(rainfall <span class="sc">==</span> <span class="st">&#39;yes&#39;</span>, </span>
<span id="cb266-7"><a href="linear-models-lm.html#cb266-7" tabindex="-1"></a>                    <span class="dv">101</span> <span class="sc">+</span> <span class="fl">2.7</span><span class="sc">*</span>temperature <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">3</span>), </span>
<span id="cb266-8"><a href="linear-models-lm.html#cb266-8" tabindex="-1"></a>                    <span class="dv">184</span> <span class="sc">+</span> <span class="fl">0.0</span><span class="sc">*</span>temperature <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">0</span>, <span class="dv">3</span>))</span>
<span id="cb266-9"><a href="linear-models-lm.html#cb266-9" tabindex="-1"></a></span>
<span id="cb266-10"><a href="linear-models-lm.html#cb266-10" tabindex="-1"></a><span class="co"># put everything into data.frame</span></span>
<span id="cb266-11"><a href="linear-models-lm.html#cb266-11" tabindex="-1"></a>incDF <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">incidence =</span> incidence,</span>
<span id="cb266-12"><a href="linear-models-lm.html#cb266-12" tabindex="-1"></a>                    <span class="at">temperature =</span> temperature,</span>
<span id="cb266-13"><a href="linear-models-lm.html#cb266-13" tabindex="-1"></a>                    <span class="at">rainfall =</span> <span class="fu">factor</span>(rainfall))</span></code></pre></div>
<p>Note, in this example we have created data, where temperature <em>appears</em> to have an effect but rainfall does not.</p>
<p>If we were given this data we would usually start by visualising it, maybe with a boxplot showing the distribution of incidence for the off and on-season and a graph plotting incidence against temperature.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="linear-models-lm.html#cb267-1" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(incDF, <span class="fu">aes</span>(<span class="at">x =</span> rainfall, <span class="at">y =</span> incidence, <span class="at">fill =</span> rainfall)) <span class="sc">+</span></span>
<span id="cb267-2"><a href="linear-models-lm.html#cb267-2" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb267-3"><a href="linear-models-lm.html#cb267-3" tabindex="-1"></a></span>
<span id="cb267-4"><a href="linear-models-lm.html#cb267-4" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(incDF, <span class="fu">aes</span>(<span class="at">x =</span> temperature, <span class="at">y =</span> incidence)) <span class="sc">+</span></span>
<span id="cb267-5"><a href="linear-models-lm.html#cb267-5" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb267-6"><a href="linear-models-lm.html#cb267-6" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&#39;lm&#39;</span>)</span>
<span id="cb267-7"><a href="linear-models-lm.html#cb267-7" tabindex="-1"></a></span>
<span id="cb267-8"><a href="linear-models-lm.html#cb267-8" tabindex="-1"></a>p1 <span class="sc">+</span> p2</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-178-1.png" style="display: block; margin: auto;" /></p>
<p>It would be reasonable to conclude that rainfall does not seem to have a strong effect on incidence whilst there seems to be a clear and positive correlation between temperature and incidence. Next we would put this through our statistical modelling machinery and test whether our predictions are right.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="linear-models-lm.html#cb268-1" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(incidence <span class="sc">~</span> temperature <span class="sc">+</span> rainfall, <span class="at">data =</span> incDF)</span>
<span id="cb268-2"><a href="linear-models-lm.html#cb268-2" tabindex="-1"></a></span>
<span id="cb268-3"><a href="linear-models-lm.html#cb268-3" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = incidence ~ temperature + rainfall, data = incDF)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.8694 -1.7518  0.1403  2.6131  8.4056 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 147.0397     6.6019  22.272  &lt; 2e-16 ***
## temperature   1.2146     0.2130   5.702 1.28e-07 ***
## rainfallyes  -0.3287     0.7309  -0.450    0.654    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.594 on 97 degrees of freedom
## Multiple R-squared:  0.2517, Adjusted R-squared:  0.2363 
## F-statistic: 16.31 on 2 and 97 DF,  p-value: 7.814e-07</code></pre>
<p>From this analysis we would conclude that temperature has a statistically significant effect on disease incidence (<em>P</em>&lt;0.001), that rainfall does not have a statistically significant effect on disease incidence (<em>P</em>=0.91), and that would be the end of it. But what about the possibility that the effect of temperature is dependent on whether it is the on- or the off-season? That is, we are interested in the interaction term temperature <span class="math inline">\(\times\)</span> rainfall. In the <code>lm()</code> function we can do this either adding the term <code>temperature:rainfall</code> to our previous model, or use the notation <code>temperature*rainfall</code>, which is short for <code>temperature + rainfall + temperature:rainfall</code></p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="linear-models-lm.html#cb270-1" tabindex="-1"></a>fitInteraction <span class="ot">&lt;-</span> <span class="fu">lm</span>(incidence <span class="sc">~</span> temperature<span class="sc">*</span>rainfall, <span class="at">data =</span> incDF)</span>
<span id="cb270-2"><a href="linear-models-lm.html#cb270-2" tabindex="-1"></a></span>
<span id="cb270-3"><a href="linear-models-lm.html#cb270-3" tabindex="-1"></a><span class="fu">summary</span>(fitInteraction)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = incidence ~ temperature * rainfall, data = incDF)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.3512 -1.1099  0.1151  1.5418  5.6447 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             198.1774     6.9041  28.704   &lt;2e-16 ***
## temperature              -0.4415     0.2232  -1.978   0.0508 .  
## rainfallyes             -93.4598     9.3205 -10.027   &lt;2e-16 ***
## temperature:rainfallyes   3.0131     0.3011  10.007   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.528 on 96 degrees of freedom
## Multiple R-squared:  0.6338, Adjusted R-squared:  0.6223 
## F-statistic: 55.37 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>In the summary we can see one additional term: <code>temperature:rainfallyes</code>, and we see that this is highly significant (<em>P</em>&lt;0.001). On the other hand, <code>temperature</code> does not appear to be a statistically significant predictor of <code>incidence</code> anymore! Beware: this would be the wrong conclusion because of the significance of the interaction term. I.e. removing <code>temperature</code> from our model, which would also remove the interaction term, would result in a much inferior model.</p>
<p>One other, and important, conclusion we can draw from this analysis is that interaction terms affect the <strong>slope</strong> of the regression line, which contrasts the additive effects we saw earlier and that only affected the <strong>intersect</strong>. And this also explains why adding linear regression lines with <code>geom_smooth</code> for stratified data we can get lines with different gradients.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="linear-models-lm.html#cb272-1" tabindex="-1"></a><span class="fu">ggplot</span>(incDF, <span class="fu">aes</span>(<span class="at">x =</span> temperature, <span class="at">y =</span> incidence, <span class="at">col =</span> rainfall)) <span class="sc">+</span></span>
<span id="cb272-2"><a href="linear-models-lm.html#cb272-2" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb272-3"><a href="linear-models-lm.html#cb272-3" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&#39;lm&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-181-1.png" style="display: block; margin: auto;" /></p>
<blockquote>
<p><strong>Note:</strong> in this example we considered interaction between a continuous and a categorical variable. Interactions between two continuous or two categorical variables are also possible and are treated in exactly the same way in <code>lm()</code>. The only difference is the (biological) interpretation of the interaction term.</p>
</blockquote>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-statistical-modelling-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mixed-effect-models-mem.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
